language: perl
perl:
  - "5.10"
  - "5.20"
  - "5.30"
sudo: false
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
install:
  - cpanm --quiet --installdeps --notest .
  - apt install mysql-server
  - cpanm --quiet DBD::mysql
