language: perl
perl:
  - "5.10"
  - "5.20"
  - "5.30"
sudo: false
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
install:
  - cpanm --quiet --installdeps --notest .
  - cpanm --quiet --notest DBD::mysql
services:
  - mysql
env:
  - MOGTEST_DBHOST=127.0.0.1 MOGTEST_DBUSER=root MOGTEST_DBPASS= MOGTEST_DBNAME=mysql
